name: AKS Node-by-Node Upgrade Syntax Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  bash-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show repo files (debug)
        run: |
          ls -R

      - name: Fix CRLF
        run: |
          sed -i 's/\r$//' scripts/aks-node-by-node-test.sh

      - name: Bash syntax check
        run: |
          bash -n scripts/aks-node-by-node-test.sh

      - name: Run script
        run: |
          bash scripts/aks-node-by-node-test.sh
